import { initializeApp, cert } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import fetch from 'node-fetch';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

dotenv.config();

// Config
const API_BASE = 'http://localhost:4000/api';
const TEST_UID = 'test-e2e-user';

async function getIdToken() {
    // Return magic token directly since we enabled E2E_TEST_MODE in backend
    return 'e2e-magic-token';
}

async function runTests() {
    console.log('🚀 Starting Backend E2E Verification...');

    // 1. Health Check
    try {
        const healthRes = await fetch('http://localhost:4000/health');
        console.log(`Health Check: ${healthRes.status} ${healthRes.status === 200 ? '✅' : '❌'}`);
    } catch (e) {
        console.error('Health Check Failed:', e.message);
        process.exit(1);
    }

    // 2. Auth Gating (Negative Test)
    const unauthorizedRes = await fetch(`${API_BASE}/tasks`);
    console.log(`Auth Gating (No Token): ${unauthorizedRes.status} ${unauthorizedRes.status === 401 ? '✅' : '❌'}`);

    // Get Token
    const token = await getIdToken();
    const headers = {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
    };
    console.log('🔑 Obtained valid Firebase ID Token (Mock)');

    // 3. Create Task
    const newTask = {
        title: 'E2E Test Task',
        description: 'Auto-generated by verification script',
        status: 'Pending',
        priority: 'High'
    };

    const createRes = await fetch(`${API_BASE}/tasks`, {
        method: 'POST',
        headers,
        body: JSON.stringify(newTask)
    });

    const body = await createRes.json();
    const createdTask = body.data || body;

    console.log(`Create Task: ${createRes.status} ${createRes.status === 201 ? '✅' : '❌'} (ID: ${createdTask.id})`);

    if (!createdTask.id) {
        console.error('Failed to create task, aborting CRUD tests');
        console.error(body);
        return;
    }

    // 4. List Tasks
    const listRes = await fetch(`${API_BASE}/tasks`, { headers });
    const listBody = await listRes.json();
    const tasks = listBody.data || listBody;
    const found = tasks.find(t => t.id === createdTask.id);
    console.log(`List Tasks: ${listRes.status} ${found ? '✅ Task Found' : '❌ Task Missing'}`);

    // 5. Update Task
    const updateRes = await fetch(`${API_BASE}/tasks/${createdTask.id}`, {
        method: 'PUT',
        headers,
        body: JSON.stringify({ status: 'Completed' })
    });
    const updateBody = await updateRes.json();
    const updatedTask = updateBody.data || updateBody;
    console.log(`Update Task: ${updateRes.status} ${updatedTask.status === 'Completed' ? '✅' : '❌'}`);

    // 6. Delete Task
    const deleteRes = await fetch(`${API_BASE}/tasks/${createdTask.id}`, {
        method: 'DELETE',
        headers
    });
    console.log(`Delete Task: ${deleteRes.status} ${deleteRes.status === 200 ? '✅' : '❌'}`);

    console.log('🎉 E2E Verification Complete!');
    process.exit(0);
}

runTests();
